### PR TITLE
added the ability to choose acl permissions such as private-read etc. 

### PR DESCRIPTION
**Pull request by jasonroland**
Please review, I have uploaded the files correctly. This will add good functionality for devs. Thank you.

### CODE REVIEW

**Comment by jasonroland** [comment]
Please review, I would like this to me merged to main branch. Thank you.

**Comment by jasonroland** [comment]
If there are any issues please let me know.

**Comment by jasonroland** [comment]
@Serdnad, have you had a chance to review?

**Comment by Serdnad** [comment]
@jasonroland Sorry, I didn't see any of this until now. Thank you so much for this PR and your other one, I'll publish a new version of the lib.

**Pull request merged**
